### ISSUE TITLE
2.0.0 release checklist

### ISSUE THREAD

**Issue by jmakeig** [marklogic/mlxprs#25]
- [x] Decide that “2.0.0” is the new version number (@mikrovvelle)
- [x] Create 2.0.0 release milestone (@jmakeig)
- [ ] Resolve [all 2.0.0 targeted issues](https://github.com/mikrovvelle/mlxprs/milestone/1). (If they shouldn’t block the release, remove the release milestone from the issue)
- [x] Update README with quick instructions and screenshot (#31)
- [ ] Blurb on audience, benefits, and capabilities for Marketing (@jmakeig)
- [ ] Screencast of Java unit testing for #49 (@jmakeig)
- [x] [Release notes](https://github.com/mikrovvelle/mlxprs/blob/master/CHANGELOG.md) (@mikrovvelle)
- [x] Push to VS Code Extension Marketplace and update metadata (@mikrovvelle)

**Comment by jmakeig** [comment]
@mikrovvelle, when you push to the marketplace can you also please update the metadata to reflect the latest README, for example, hiding references to “mlxprs”?

**Comment by jmakeig** [comment]
Still need to do screencast (#52) and broader marketing, but I’m closing this as “done enough”.
